(async()=>{try{
const K='vicious_sync_v4',DONE='vicious_synced_days_v4',B=1,S=ms=>new Promise(r=>setTimeout(r,ms)),T=e=>(e?.textContent||'').replace(/\s+/g,' ').trim(),N=s=>{const m=String(s||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null},P=h=>new DOMParser().parseFromString(h,'text/html');
if(!location.pathname.includes('/results/classmatch/fight/daily_detail'))throw Error('日別戦績一覧で実行してください');
const F=async u=>{const r=await fetch(u,{credentials:'include',cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const h=await r.text();return[h,P(h)]};
const base=new URL(location.href),day=T(document.querySelector('h3 .datetime')),venue=T(document.querySelector('h3 .col-stand')),sig=(base.searchParams.get('ts')||'')+'|'+(base.searchParams.get('param')||'')+'|'+day+'|'+venue;
let done=JSON.parse(localStorage.getItem(DONE)||'[]');
if(done.includes(sig))return completion(`同期済み: ${day} ${venue}（取得をスキップ）`);
let st=JSON.parse(localStorage.getItem(K)||'null');
if(!st||st.sig!==sig)st={sig,day,venue,max:1,next:1,q:[],r:[]};
for(const a of document.querySelectorAll('.page-send a[href*="daily_detail"]')){try{st.max=Math.max(st.max,+(new URL(a.href,location.href).searchParams.get('page')||1))}catch{}}
if(st.next<=st.max){let d;if(st.next===+(base.searchParams.get('page')||1))d=document;else{const u=new URL(location.href);u.searchParams.set('page',st.next);[,d]=await F(u)}for(const a of d.querySelectorAll('a.vs-detail[href*="match_detail"]')){const h=new URL(a.getAttribute('href'),location.href).href;if(!st.q.some(x=>x.h===h)&&!st.r.some(x=>x._h===h)){let n=T(a.querySelector('p.fz-xs.fw-b'));if(/^\d+WINS$/i.test(n))n='';st.q.push({h,t:T(a.querySelector('.datetime')),w:a.classList.contains('win')?'win':a.classList.contains('lose')?'lose':null,n})}}st.next++;localStorage.setItem(K,JSON.stringify(st));return completion(`一覧 ${st.next-1}/${st.max} 読込済・試合 ${st.q.length+st.r.length}件`)}
const score=li=>{const o={};for(const dl of li.querySelectorAll('dl')){const k=T(dl.querySelector('dt')).replace(/\s+/g,''),v=T(dl.querySelector('dd'));if(k.includes('スコア'))o.score=N(v);else if(k==='撃墜')o.kills=N(v);else if(k==='被撃墜')o.deaths=N(v);else if(k.includes('EXバーストダメージ'))o.burstDamage=N(v);else if(k.includes('与ダメージ'))o.damageDealt=N(v);else if(k.includes('被ダメージ'))o.damageTaken=N(v)}const c=[...li.classList].find(x=>/^rank-band\d+$/.test(x));o.rank=c?+c.replace('rank-band',''):null;const im=li.querySelector('img.item-icon-img');if(im){let s=im.getAttribute('data-original')||im.getAttribute('src')||'';try{const u=new URL(s,location.href);u.search='';o.machineImage=u.href}catch{o.machineImage=s}}return o};
const timeline=h=>{const d=P(h),s=[...d.scripts].map(x=>x.textContent||'').find(x=>x.includes('var dataset')&&x.includes('vis.DataSet'))||'',e=[],sec=(a,b,c)=>+a*60 + +b + +c/100,re=/var start_time = new Date\(0,\s*0,\s*0,\s*(\d+),\s*(\d+),\s*(\d+)\);\s*(?:var end_time = new Date\(0,\s*0,\s*0,\s*(\d+),\s*(\d+),\s*(\d+)\);\s*)?dataset\.push\(\{\s*id:\s*\d+,\s*group:\s*"([^"]+)",\s*start:\s*start_time(?:,\s*end:\s*end_time)?(?:,\s*className:'([^']+)')?(?:,\s*type:'([^']+)')?\s*\}\);/g;let m;while(m=re.exec(s))e.push({g:m[7],a:sec(m[1],m[2],m[3]),b:m[4]!=null?sec(m[4],m[5],m[6]):null,c:m[8]||null,t:m[9]||null});return e};
for(let z=0;z<B&&st.q.length;z++){const m=st.q.shift();try{const[h,d]=await F(m.h),names=[...d.querySelectorAll('#panel1 .name')].map(T).filter(Boolean);let i=m.n?names.indexOf(m.n):-1;if(i<0)i=0;const rows=[...d.querySelectorAll('#panel3 li.item')].map(score),g=['team1-1','team1-2','team2-1','team2-2'][i],ev=timeline(h).filter(x=>x.g===g),de=ev.filter(x=>x.t==='point').map(x=>x.a),bu=ev.filter(x=>/^exbst-(f|s|e)$/.test(x.c||'')),rd=ev.filter(x=>x.c==='ex'),fd=de[0]??null,fb=bu[0]?.a??null,held=de.filter(x=>rd.some(y=>y.a<=x&&(y.b==null||x<=y.b+.001))),u=new URL(m.h),ts=u.searchParams.get('ts')||null;st.r.push({_h:m.h,matchId:ts,matchTs:ts?+ts:null,time:m.t,result:m.w,selfName:m.n||names[i]||null,self:rows[i]||null,players:names,scoreRows:rows,deathsSec:de,burst:{count:bu.length,types:bu.map(x=>x.c.slice(-1).toUpperCase()),activationsSec:bu.map(x=>x.a),firstBeforeDeath:fb!=null&&(fd==null||fb<fd),heldDeathCount:held.length}})}catch(e){st.r.push({_h:m.h,matchId:null,time:m.t,result:m.w,error:String(e.message||e)})}await S(80)}
if(st.q.length){localStorage.setItem(K,JSON.stringify(st));return completion(`詳細 ${st.r.length}件完了・残り ${st.q.length}件`)}
const clean=st.r.map(({_h,...x})=>x),good=clean.filter(x=>!x.error),wins=good.filter(x=>x.result==='win').length,avg=a=>{a=a.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null},out={schemaVersion:4,source:'GUNDAM VS. MOBILE / EXVS2IB',day:st.day,venue:st.venue,summary:{matches:good.length,wins,losses:good.length-wins,winRate:good.length?wins/good.length:null,avgDamageDealt:avg(good.map(x=>x.self?.damageDealt)),avgDamageTaken:avg(good.map(x=>x.self?.damageTaken)),avgBurstCount:avg(good.map(x=>x.burst?.count))},matches:clean};
done=[...new Set([...done,sig])].slice(-120);localStorage.setItem(DONE,JSON.stringify(done));localStorage.removeItem(K);completion(JSON.stringify(out))
}catch(e){completion('ERROR: '+String(e.message||e))}})();